"use client";

import "./globals.css";

// export const metadata = {
// 	title: "Lens Social",
// 	description: "Generated by create next app",
// };

// RainbowKit -------------------------------------------------------------------
import "@rainbow-me/rainbowkit/styles.css";
import {
	ConnectButton,
	getDefaultWallets,
	RainbowKitProvider,
} from "@rainbow-me/rainbowkit";
import { configureChains, createClient, WagmiConfig } from "wagmi";
import { polygon, polygonMumbai } from "wagmi/chains";
import { alchemyProvider } from "wagmi/providers/alchemy";
import { publicProvider } from "wagmi/providers/public";

const { chains, provider } = configureChains(
	[polygon, polygonMumbai],
	[publicProvider()]
);

const { connectors } = getDefaultWallets({
	appName: "My RainbowKit App",
	chains,
});

const wagmiClient = createClient({
	autoConnect: true,
	connectors,
	provider,
});
// -------------------------------------------------------------------------------

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<WagmiConfig client={wagmiClient}>
					<RainbowKitProvider chains={chains}>
						<div className="p-3 flex justify-end">
							<ConnectButton />
						</div>
						{children}
					</RainbowKitProvider>
				</WagmiConfig>
			</body>
		</html>
	);
}
